---

all:
  children:
    hyporvisors:
      hosts:
        proxmox01:
          ansible_host: 192.168.0.254
#         172.16.0.1
#         172.16.10.1 
    servers:
      children:
        Firewall:
          hosts:
            Pf01:
              ansible_host: 192.160.0.250
        ubuntu2204:
          hosts:
            ansible01:
              ansible_host: 172.16.0.5          
            pihole01:
              ansible_host: 172.16.0.10
            gitlab01:
              ansible_host: 172.16.0.20
            syslog01:
              ansible_host: 172.16.0.30
          children:
            GameServers:
              hosts:
                minecraft01:
                  ansible_host: 172.16.10.10
                satisfactory01:
                  ansible_host: 172.16.10.20
                ArkSurv01:
                  ansible_host: 172.16.10.30
