---

Apt_List:
  - curl
  - wget
  - file
  - tar
  - bzip2
  - gzip
  - unzip
  - bsdmainutils
  - python3
  - util-linux
  - ca-certificates
  - binutils
  - bc
  - jq
  - tmux
  - netcat
  - lib32gcc-s1
  - lib32stdc++6
  - openjdk-17-jre
  - libsdl2-2.0-0:i386