lab:
  Aalborg:
    Routers:
      Aalborg-1: 10.10.0.1
      Aalborg-2: 10.10.0.2
      Aalborg-3: 10.10.0.3    
  Aarhus:
    Routers:
      Aarhus-1: 10.20.0.1
      Aarhus-2: 10.20.0.2
      Aarhus-3: 10.20.0.3
  Fredericia:
    Routers:
      Fredericia-1: 10.30.0.1
      Fredericia-2: 10.30.0.2
      Fredericia-3: 10.30.0.3
  København:
    Routers:
      København-1: 10.40.0.1
      København-2: 10.40.0.2
      København-3: 10.40.0.3